services:
  - type: web
    name: shoes-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false # Set this in the Render dashboard to your MongoDB Atlas URI
    autoDeploy: true
    rootDir: backend
